---
#
#- name: Cleanup old staging directory
#  ansible.builtin.file:
#    path: "{{ local_staging_dir }}"
#    state: absent
#  delegate_to: localhost

- name: Ensure staging directory exists
  ansible.builtin.file:
    path: "{{ local_staging_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Download the release archive from GitLab
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "{{ local_release_archive }}"
    mode: '0644'
  delegate_to: localhost

- name: Extract the release archive
  ansible.builtin.unarchive:
    src: "{{ local_release_archive }}"
    dest: "{{ local_staging_dir }}"
    remote_src: yes
  delegate_to: localhost

---

#- name: Copy release to Splunk apps directory
#  ansible.builtin.copy:
#    src: "{{ local_staging_dir }}/"
#    dest: "{{ splunk_apps_dir }}"
#    remote_src: yes
#
#- name: Trigger Splunk to reload apps
#  ansible.builtin.command: '/opt/splunk/bin/splunk apply shcluster-bundle -target captain_url -auth admin:changeme'
#  delegate_to: localhost
#  become: true
#  become_user: splunk

